services:
  react-app:
      build:
        context: ./simple-react-app
        dockerfile: react.dockerfile
      image: ${REACT_IMAGE_NAME}
      container_name: ${REACT_CONTAINER_NAME}
      volumes:
        - type: bind
          source: ./simple-react-app
          target: /app
        - /app/node_modules
      ports:
        - "3000:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true
      restart: always
      depends_on:
        - symfony-app
  symfony-app:
      build:
        context: ./symfony-6-rest-api
        dockerfile: symfony.dockerfile
      image: ${SF_IMAGE_NAME}
      container_name: ${SF_CONTAINER_NAME}
      ports:
        - "8000:8000"
      restart: always
      depends_on:
        - pgdb
  pgdb:
    build:
      context: ./postgres-database
      dockerfile: postgres.dockerfile
    image: ${PG_IMAGE_NAME}
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - symfonydb:/data/postgres-code
    ports:
      - "5435:5432"
    restart: unless-stopped

volumes:
    symfonydb:
      external: true